from enum import Enum


class USAState(Enum):
    Az = "arizona"
    Ca = "california"
    Co = "colorado"
    Ct = "connecticut"
    Fl = "florida"
    Ga = "georgia"
    Ia = "iowa"
    Il = "illinois"
    Ma = "massachusets"
    Md = "maryland"
    Mi = "michigan"
    Mt = "montana"
    Nc = "north_carolina"
    Nh = "new_hampshire"
    Nj = "new_jersey"
    Nv = "nevada"
    Oh = "ohio"
    Ri = "rhode_island"
    Sd = "south_dakota"
    Sc = "south_carolina"
    Tn = "tennessee"
    Tx = "texas"
    Vt = "vermont"
    Wa = "washington"
    Wi = "wisconsin"
